### ISSUE TITLE
Unable to make more than 50 daily interactions

### ISSUE THREAD

**Issue by javicaballero** [JudiniLabs/code-gpt-docs#310]
There seems to be an error on the platform. I am unable to make more than 50 daily interactions, despite having subscribed to the CodeGPT Plus Professional plan since yesterday. Is this a bug?

This issue is urgent as I have a live website with a new product, and this error is severely affecting its launch.

Thank you

Now I paid for the $19.99 USD plan and it unlocked 100 daily interactions, which I've already used up. This is not right.

![imagen](https://github.com/user-attachments/assets/29c75d5a-073e-4c94-aa90-760e065e6aa6)

It's in spanish:
![imagen](https://github.com/user-attachments/assets/08591086-12a6-430f-88a5-1f7a36ce8b8d)

**Comment by Adel242** [comment]
Yes, it is possible that there may be temporary changes in interaction limits due to various circumstances, including misuse of the application by some users. However, these changes are generally temporary and are expected to be restored to their original limits once the issue is resolved. Is there anything else I can assist you with today?

**Comment by davila7** [comment]
We are reviewing your account internally.

For any issues with your CodeGPT Plus account, you can write to us at this email: [hello@codegpt.co](mailto:hello@codegpt.co)
